### ISSUE TITLE
issue:route On store delete, must be deleted from user schema as well.

### ISSUE THREAD

**Issue by 13x54n** [Zetsy-FYP/zetsy-main#2]
Currently, the `userRouter` for user consists of a new user, get user, add a store, email, and delete the user but users can delete the store and there's no controller to just remove the store id in
```
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const UserSchema = new Schema({
  userUid: {
    type: String,
    unique: true,
  },
  email: String,
  stores: [
    {
      type: Schema.Types.ObjectId,
      ref: "Store",
    },
  ],
});

module.exports = mongoose.model("User", UserSchema);

```

So, need to add new controller to `UserRouter` route where if store delete requested then just remove that requested store from User Schema.

**Comment by surajgaire14** [comment]
I have linked a pull request where I have created a _patch_ request where when the store is deleted it is deleted from the user document as well @13x54n
